# Import des librairies nécessaires

In [ ]:
import pandas as pd
import json
import numpy as np
import os
import re
import time
import torch
import joblib
import sys
import argparse
import dotenv 
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.dates as mdates

from transformers import BertTokenizer, BertModel
from transformers import RobertaTokenizer, RobertaModel
from sentence_transformers import SentenceTransformer
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud
from wordcloud import STOPWORDS
from scipy.stats import ttest_ind
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler

from src.models.training_evaluation import train_and_tune_models

# Chargement des données

données issues de : https://arxiv.org/pdf/2310.08903

https://github.com/Jihuai-wpy/SeqXGPT

In [53]:
# Chargement des données écrites par l'humain
human_lines_path = 'data/raw/en_human_lines.jsonl'
human_df = pd.read_json(human_lines_path, lines=True)
print("Le nombre de textes écrits par l'humaine est  : ", human_df.shape[0])

Le nombre de textes écrits par l'humaine est  :  6000

In [54]:
# Chargement des données générées par le modèle GPT-2
gpt2_lines_path = 'data/raw/en_gpt2_lines.jsonl'
gpt2_df = pd.read_json(gpt2_lines_path, lines=True)
print("Le nombre de textes générés par le modèle GPT-2 est  : ", gpt2_df.shape[0])

Le nombre de textes générés par le modèle GPT-2 est  :  6000

In [55]:
# Chargement des données générées par le modèle GPT-3
gpt3_lines_path = 'data/raw/en_gpt3_lines.jsonl'
gpt3_df = pd.read_json(gpt3_lines_path, lines=True)
print("Le nombre de textes générés par le modèle GPT-3 est  : ", gpt3_df.shape[0])

Le nombre de textes générés par le modèle GPT-3 est  :  6000

In [56]:
# Chargement des données générées par le modèle LLaMA
llama_lines_path = 'data/raw/en_llama_lines.jsonl'
llama_df = pd.read_json(llama_lines_path, lines=True)
print("Le nombre de textes générés par le modèle LLaMA est  : ", llama_df.shape[0])

Le nombre de textes générés par le modèle LLaMA est  :  5904

# Prétraitement des données

## Sélection des données pour la base

In [57]:
# Tirage aléatoire de 2000 textes dans chaque dataframe issu des LLMs
gpt2_sample = gpt2_df.sample(n=2000, random_state=42)
gpt3_sample = gpt3_df.sample(n=2000, random_state=42)
llama_sample = llama_df.sample(n=2000, random_state=42)

# Concaténation des échantillons dans un seul dataframe
sample_df = pd.concat([gpt2_sample, gpt3_sample, llama_sample], ignore_index=True)

# Ajout de toutes les données écrites par l'humain
sample_df = pd.concat([sample_df, human_df], ignore_index=True)

# Mélanger les lignes du dataframe
sample_df = sample_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Ajout d'une colonne pour la longueur des textes
sample_df['text_len'] = sample_df['text'].apply(len)

sample_df = sample_df.drop(columns=["prompt_len"])

# Sauvegarde du dataframe échantillonné dans un fichier JSONL
sample_df.to_json('data/en_sample_lines.jsonl', orient='records', lines=True)

# Affichage du nombre total de textes   
print("Le nombre total de textes est : ", sample_df.shape[0])
# Affichage du nombre de textes par source
print("Le nombre de textes par source est :")
print(sample_df['label'].value_counts())

# Affichage du début du dataframe
print("Aperçu du dataframe échantillonné :")
print(sample_df.head())

Le nombre total de textes est :  12000
Le nombre de textes par source est :
label
human     6000
gpt2      2000
llama     2000
gpt3re    2000
Name: count, dtype: int64
Aperçu du dataframe échantillonné :
                                                text  label  text_len
0  In the triplet form, O 2 molecules are paramag...   gpt2      1477
1  Studies on income inequality and growth have s...  human       605
2  JCF Capital ULC announced on Tuesday a deal wi...   gpt2       424
3  The right to create private schools in Germany...  human       622
4  during the week of 2015-05-11 Aatrox was last ...   gpt2      1361

## Tokenisation du texte

In [58]:
# Tokenisation des textes avec BERT
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

def tokenize_text_bert(text):
    return bert_tokenizer.tokenize(text)

# def tokenize_word(text):
#     return word_tokenize(text)

sample_df['bert_tokens'] = sample_df['text'].apply(tokenize_text_bert)
# sample_df['word_tokens'] = sample_df['text'].apply(tokenize_word)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

KeyboardInterrupt:

## Découpe de la base de données en base d'entraînement et base de test

In [ ]:
# Découpe de la base de données en base d'entraînement et de test (80% - 20%)
train_df, test_df = train_test_split(sample_df, test_size=0.2, random_state=42)
# Sauvegarde des dataframes d'entraînement et de test dans des fichiers JSONL
train_df.to_json('data/en_train_lines.jsonl', orient='records', lines=True)
test_df.to_json('data/en_test_lines.jsonl', orient='records', lines=True)

In [ ]:
text_train = train_df['text']
label_train = train_df['label']
bert_token_train = train_df['bert_tokens']
# word_token_train = train_df['word_tokens']

text_test = test_df['text']
label_test = test_df['label']
bert_token_test = test_df['bert_tokens']
# word_token_test = test_df['word_tokens']

In [ ]:
sample_df.head()

,text,label,text_len,bert_tokens
0,"In the triplet form, O 2 molecules are paramag...",gpt2,1477,"[In, the, triple, ##t, form, ,, O, 2, molecule..."
1,Studies on income inequality and growth have s...,human,605,"[Studies, on, income, inequality, and, growth,..."
2,JCF Capital ULC announced on Tuesday a deal wi...,gpt2,424,"[J, ##CF, Capital, U, ##LC, announced, on, Tue..."
3,The right to create private schools in Germany...,human,622,"[The, right, to, create, private, schools, in,..."
4,during the week of 2015-05-11 Aatrox was last ...,gpt2,1361,"[during, the, week, of, 2015, -, 05, -, 11, A,..."

## Définition de caractéristiques des données

### Embeddings des textes

In [ ]:
# Encodage des textes avec Bag-of-word
# Créer et entraîner le vectorizer
vectorizer = CountVectorizer(max_features=1000)  # Limiter à 1000 mots les plus fréquents
# Entraîner le vectorizer sur les textes d'entraînement
vectorizer.fit(text_train)

# Transformer les textes d'entraînement et de test en vecteurs
text_train_counts = vectorizer.transform(text_train)
text_test_counts = vectorizer.transform(text_test)

# On transforme tous les textes en vecteurs
# bow_vectors = vectorizer.transform(sample_df["text"]).toarray().tolist()

# Et on ajoute la colonne
# sample_df["bow_vector"] = bow_vectors

In [ ]:
# Encodage des textes avec TF-IDF
# Création du vectorizer avec 1000 mots max
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

# Apprentissage du vocabulaire sur les textes d'entraînement
tfidf_vectorizer.fit(text_train)

# Transformation des textes d'entraînement et de test en vecteurs TF-IDF
text_train_tfidf = tfidf_vectorizer.transform(text_train)
text_test_tfidf = tfidf_vectorizer.transform(text_test)

# Application sur tous les textes du dataset
# tfidf_vectors = tfidf_vectorizer.transform(sample_df["text"])

# Conversion en liste et ajout au DataFrame
# sample_df["tfidf_vector"] = tfidf_vectors.toarray().tolist()

In [ ]:
sample_df.head()

,text,label,text_len,bert_tokens,bow_vector,tfidf_vector
0,"In the triplet form, O 2 molecules are paramag...",gpt2,1477,"[In, the, triple, ##t, form, ,, O, 2, molecule...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,Studies on income inequality and growth have s...,human,605,"[Studies, on, income, inequality, and, growth,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,JCF Capital ULC announced on Tuesday a deal wi...,gpt2,424,"[J, ##CF, Capital, U, ##LC, announced, on, Tue...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,The right to create private schools in Germany...,human,622,"[The, right, to, create, private, schools, in,...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.09950674799129947, 0.0,..."
4,during the week of 2015-05-11 Aatrox was last ...,gpt2,1361,"[during, the, week, of, 2015, -, 05, -, 11, A,...","[0, 16, 0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,...","[0.0, 0.3365636073184281, 0.0, 0.0, 0.13240910..."

In [ ]:
# Embedding des tokens avec Word2Vec (à entraîner sur les données d'entraînement)
w2v_model = Word2Vec(sentences=bert_token_train.tolist(), vector_size=100, window=5, min_count=1, workers=4)

def get_text_embedding(tokens, model, vector_size=100):
    vecs = [model.wv[word] for word in tokens if word in model.wv]
    if len(vecs) > 0:
        return np.mean(vecs, axis=0)
    else:
        return np.zeros(vector_size)

# Appliquer à chaque ligne pour créer une colonne d'embedding
# sample_df['w2v_embedding'] = sample_df['bert_tokens'].apply(lambda tokens: get_text_embedding(tokens, w2v_model, vector_size=100))

In [ ]:
# Transformer les textes d'entraînement et de test en embeddings Word2Vec
text_train_w2v = text_train.apply(lambda tokens: get_text_embedding(tokens, w2v_model, vector_size=100))
text_test_w2v = text_test.apply(lambda tokens: get_text_embedding(tokens, w2v_model, vector_size=100))

In [ ]:
type(text_test)

pandas.core.series.Series

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
from tqdm import tqdm

# Initialisation
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_name = "bert-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name).to(device)
model.eval()

# Fonction batchée pour obtenir les embeddings
def compute_bert_embeddings(texts, batch_size=32, max_length=512):
    all_embeddings = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Calcul des embeddings BERT"):
        batch_texts = texts[i:i+batch_size]
        
        # Tokenisation batch
        inputs = tokenizer(batch_texts, return_tensors="pt", padding=True,
                           truncation=True, max_length=max_length)
        
        inputs = {key: val.to(device) for key, val in inputs.items()}
        
        with torch.no_grad():
            outputs = model(**inputs)
        
        # Moyenne sur la séquence pour chaque exemple
        batch_embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
        all_embeddings.append(batch_embeddings)

    return np.vstack(all_embeddings)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

In [ ]:
# Supposons que tu as deux listes : `train_texts` et `test_texts`
train_bert_embeddings = compute_bert_embeddings(text_train.to_list())
test_bert_embeddings = compute_bert_embeddings(text_test.to_list())

Calcul des embeddings BERT: 100%|██████████| 300/300 [04:54<00:00,  1.02it/s]
Calcul des embeddings BERT: 100%|██████████| 75/75 [01:14<00:00,  1.01it/s]

In [ ]:
np.save("data/train_bert_embeddings.npy", train_bert_embeddings)
np.save("data/test_bert_embeddings.npy", test_bert_embeddings)

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
from tqdm import tqdm

# Chargement du modèle RoBERTa
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
roberta_model_name = "roberta-base"

roberta_tokenizer = AutoTokenizer.from_pretrained(roberta_model_name)
roberta_model = AutoModel.from_pretrained(roberta_model_name).to(device)
roberta_model.eval()

# Fonction d'embedding RoBERTa
def compute_roberta_embeddings(texts, batch_size=32, max_length=512, save_path=None):
    if not isinstance(texts, list) or not all(isinstance(t, str) for t in texts):
        raise ValueError("L'entrée doit être une liste de chaînes de caractères (List[str])")
    
    all_embeddings = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Calcul des embeddings RoBERTa"):
        batch_texts = texts[i:i+batch_size]

        inputs = roberta_tokenizer(batch_texts,
                                   return_tensors="pt",
                                   padding=True,
                                   truncation=True,
                                   max_length=max_length)
        
        inputs = {key: val.to(device) for key, val in inputs.items()}

        with torch.no_grad():
            outputs = roberta_model(**inputs)
        
        # Moyenne sur les tokens
        batch_embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
        all_embeddings.append(batch_embeddings)

    all_embeddings = np.vstack(all_embeddings)

    if save_path:
        np.save(save_path, all_embeddings)

    return all_embeddings

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np

# Chargement du modèle SBERT
sbert_model = SentenceTransformer("all-MiniLM-L6-v2")  # Tu peux aussi tester : "paraphrase-mpnet-base-v2"

# Fonction d'embedding SBERT
def compute_sbert_embeddings(texts, batch_size=32, save_path=None):
    if not isinstance(texts, list) or not all(isinstance(t, str) for t in texts):
        raise ValueError("L'entrée doit être une liste de chaînes de caractères (List[str])")
    
    embeddings = sbert_model.encode(texts,
                                    batch_size=batch_size,
                                    show_progress_bar=True,
                                    convert_to_numpy=True)
    
    if save_path:
        np.save(save_path, embeddings)
    
    return embeddings

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# SBERT
train_sbert = compute_sbert_embeddings(text_train.to_list(), save_path="data/train_sbert.npy")
test_sbert = compute_sbert_embeddings(text_test.to_list(), save_path="data/test_sbert.npy")

Batches:   0%|          | 0/300 [00:00<?, ?it/s]

Batches:   0%|          | 0/75 [00:00<?, ?it/s]

In [ ]:
# RoBERTa
train_roberta = compute_roberta_embeddings(text_train.to_list(), save_path="data/train_roberta.npy")
test_roberta = compute_roberta_embeddings(text_test.to_list(), save_path="data/test_roberta.npy")

### Caractéristiques issues de https://aclanthology.org/2022.coling-1.573.pdf

In [ ]:
from src.features_definition import extract_stylistic_features, extract_complexity_features, extract_psychological_features

[nltk_data] Downloading package words to C:\Users\hp/nltk_data...
[nltk_data]   Unzipping corpora\words.zip.
[nltk_data] Downloading package stopwords to C:\Users\hp/nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt_tab to C:\Users\hp/nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package wordnet to C:\Users\hp/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\hp/nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package sentiwordnet to
[nltk_data]     C:\Users\hp/nltk_data...
[nltk_data]   Unzipping corpora\sentiwordnet.zip.

In [ ]:
# Caractéristiques stylistiques 
## Quote Frequency (QF) : fréquence des guillemets ", ', «, », etc.
## Ponctuation Frequency (PF)  : fréquence des ., ;, :, !, ?, etc.
## Punctuation Types (PT) : nombre de formes uniques de ponctuation
## Exclamation Frequency (EF) : fréquence des points d'exclamation !
## Stopwords Frequency (SWF) : fréquence des mots vides (stopwords) (en utilisant nltk)
## Camel-Case Frequency (CCF) : fréquence des mots commençant par une majuscule suivi d'au moins une minuscule
## Négations Frequency (NF) : fréquence des mots de négation (not, no, never, etc.)
## Noms propres Frequency (NPF) :  fréquence des étiquettes POS NNP et NNPS
## Mentions d'utilisateurs : Fréquence de @
## Hashtags : Fréquence de #
## Mots mals orthographiés : Fréquence de mots non considérés comme valide par PyEnchant
## Mots manquants dans le vocabulaire : Fréquence de mots non présents dans le dictionnaire de SentiWordNet
## Noms : Fréquence de POS tags NN, NNS, NNP, NNPS
## Mots au passé : Fréquence de POS tags VBD, VBN
## Verbes : Fréquence de POS tags VB, VBP, VBZ, VBD et VBG
## Mots interrogatifs : Fréquence de POS tags WRB, WDT et WP

# Caractéristiques de complexité
## Nombre de mots : nombre total de mots
## Longueur moyenne des mots : nombre moyen de caractères par mot
## TTR : Rapport entre le nombre de mots de vocabulaire uniques et le nombre total de mots
## MTLD : Mesure du TTR pour des segments de texte de plus en plus longs

# Caractéristique psychologique
## Score de sentiment : somme des scores SentiWordNet pour tous les mots de vocabulaire disponibles

In [ ]:
train_df = pd.read_json('data/en_train_lines.jsonl', lines=True)
test_df = pd.read_json('data/en_test_lines.jsonl', lines=True)

In [ ]:
bert_token_train = train_df['bert_tokens']
bert_token_test = test_df['bert_tokens']
text_train = train_df['text']
text_test = test_df['text']

In [ ]:
# Caractéristiques stylistiques pour données d'entraînement 
extractor_stylistic_train = extract_stylistic_features(text_train, bert_token_train)
stylistic_features_train = extractor_stylistic_train.extract_features()

# Caractéristiques stylistiques pour données de test
extractor_stylistic_test = extract_stylistic_features(text_test, bert_token_test)
stylistic_features_test = extractor_stylistic_test.extract_features()

In [ ]:
# Caractéristiques complexité pour données d'entraînement
extractor_complexity_train = extract_complexity_features(text_train, bert_token_train)
complexity_features_train = extractor_complexity_train.extract_features()

# Caractéristiques complexité pour données de test
extractor_complexity_test = extract_complexity_features(text_test, bert_token_test)
complexity_features_test = extractor_complexity_test.extract_features()

In [ ]:
# Caractéristiques psychologiques pour données d'entraînement
extractor_sentiment_train = extract_psychological_features(text_train, bert_token_train)
sentiment_features_train = extractor_sentiment_train.extract_features()

# Caractéristiques psychologiques pour données de test
extractor_sentiment_test = extract_psychological_features(text_test, bert_token_test)
sentiment_features_test = extractor_sentiment_test.extract_features()

In [ ]:
np.save("data/stylistic_features_train.npy", stylistic_features_train)
np.save("data/stylistic_features_test.npy", stylistic_features_test)
np.save("data/complexity_features_train.npy", complexity_features_train)
np.save("data/complexity_features_test.npy", complexity_features_test)
np.save("data/sentiment_features_train.npy", sentiment_features_train)
np.save("data/sentiment_features_test.npy", sentiment_features_test)

### Regroupement de toutes les features pour les données d'entraînement et de test

In [ ]:
# Pour charger directement les données enregistrées
train_df = pd.read_json('data/en_train_lines.jsonl', lines=True)
test_df = pd.read_json('data/en_test_lines.jsonl', lines=True)

bert_token_train = train_df['bert_tokens']
bert_token_test = test_df['bert_tokens']

In [ ]:
# Pour charger directement les données enregistrées
label_train = train_df['label']
label_test = test_df['label']

text_train_bert = np.load('data/embeddings/train_bert_embeddings.npy')
text_test_bert = np.load('data/embeddings/test_bert_embeddings.npy')

text_train_roberta = np.load('data/embeddings/train_roberta.npy')
text_test_roberta = np.load('data/embeddings/test_roberta.npy')

text_train_sbert = np.load('data/embeddings/train_sbert.npy')
text_test_sbert = np.load('data/embeddings/test_sbert.npy')

In [ ]:
# Pour charger directement les données enregistrées
stylistic_features_train = np.load('data/features/stylistic_features_train.npy', allow_pickle=True)
complexity_features_train = np.load('data/features/complexity_features_train.npy', allow_pickle=True)
sentiment_features_train = np.load('data/features/sentiment_features_train.npy', allow_pickle=True)

stylistic_features_test = np.load('data/features/stylistic_features_test.npy', allow_pickle=True)
complexity_features_test = np.load('data/features/complexity_features_test.npy', allow_pickle=True)
sentiment_features_test = np.load('data/features/sentiment_features_test.npy', allow_pickle=True)

In [ ]:
stylistic_columns = [
    "quote_frequency",
    "punctuation_count",
    "unique_punctuation_count",
    "exclamation_frequency",
    "stopword_frequency",
    "camel_case_frequency",
    "negation_frequency",
    "proper_noun_frequency",
    "user_mentions_frequency",
    "hashtag_frequency",
    "misspelled_words",
    "oov_frequency",
    "noun_frequency",
    "past_tense_frequency",
    "verb_frequency",
    "interrogative_frequency"
]

complexity_columns = [
    "word_count",
    "mean_word_lenght",
    "ttr",
    "mtld"
]

sentiment_columns = ["sentiment_score"]

In [ ]:
# Modifier le nom des colonnes
stylistic_features_train = pd.DataFrame(stylistic_features_train, columns=stylistic_columns)
stylistic_features_test = pd.DataFrame(stylistic_features_test, columns=stylistic_columns)

complexity_features_train = pd.DataFrame(complexity_features_train, columns=complexity_columns)
complexity_features_test = pd.DataFrame(complexity_features_test, columns=complexity_columns)

sentiment_features_train = pd.DataFrame(sentiment_features_train, columns=sentiment_columns)
sentiment_features_test = pd.DataFrame(sentiment_features_test, columns=sentiment_columns)

In [ ]:
# Regrouper les features stylistiques, de complexité et psychologiques, les textes et les embeddings des données d'entraînement
train_df = pd.DataFrame({
    'text': text_train,
    'label': label_train,
    'bert_tokens': bert_token_train,
    'bow_vector': text_train_counts.toarray().tolist(),
    'tfidf_vector': text_train_tfidf.toarray().tolist(),
    'w2v_embedding': text_train_w2v.tolist(),
    'bert_embedding': text_train_bert.tolist(),
    'roberta_embedding': text_train_roberta.tolist(),
    'sbert_embedding': text_train_sbert.tolist(),
})
train_df = pd.concat([train_df, stylistic_features_train, complexity_features_train, sentiment_features_train], axis=1)

# Regrouper les features stylistiques, de complexité et psychologiques, les textes et les embeddings des données de test
test_df = pd.DataFrame({
    'text': text_test,
    'label': label_test,
    'bert_tokens': bert_token_test,
    'bow_vector': text_test_counts.toarray().tolist(),
    'tfidf_vector': text_test_tfidf.toarray().tolist(),
    'w2v_embedding': text_test_w2v.tolist(),
    'bert_embedding': text_test_bert.tolist(),
    'roberta_embedding': text_test_roberta.tolist(),
    'sbert_embedding': text_test_sbert.tolist(),
})
test_df = pd.concat([test_df, stylistic_features_test, complexity_features_test, sentiment_features_test], axis=1)

# Sauvegarde des dataframes d'entraînement et de test dans des fichiers JSONL
train_df.to_json('data/en_train_all_features.jsonl', orient='records', lines=True)
test_df.to_json('data/en_test_all_features.jsonl', orient='records', lines=True)

# Analyse descriptive

## Analyse élémentaire

In [ ]:
# Affichage du nombre de textes dans les dataframes d'entraînement et de test
print("Le nombre de textes dans le dataframe d'entraînement est : ", train_df.shape[0])
print("Le nombre de textes dans le dataframe de test est : ", test_df.shape[0])

# Affichage du nombre de textes par source dans les dataframes d'entraînement et de test
print("Le nombre de textes par source dans le dataframe d'entraînement est :")
print(train_df['label'].value_counts())
print("Le nombre de textes par source dans le dataframe de test est :")
print(test_df['label'].value_counts())

In [ ]:
# Affichage de la distribution de la longueur des textes par label

plt.figure(figsize=(10, 6))
sns.violinplot(x="label", y="text_len", data=sample_df)
plt.title("Distribution (violon) de la longueur des textes par label")
plt.xlabel("Label")
plt.ylabel("Longueur du texte")
plt.show()

In [ ]:
# Création du FacetGrid avec un graphique par label
g = sns.FacetGrid(sample_df, col="label", col_wrap=3, height=4, sharex=False, sharey=False)

# Ajout de l'histogramme dans chaque sous-plot
g.map(plt.hist, "text_len", bins=30, color="skyblue", edgecolor="black")

# Ajout des titres et labels
g.set_titles(col_template="Label: {col_name}")
g.set_axis_labels("Longueur du texte", "Nombre de textes")
plt.subplots_adjust(top=0.9)
g.fig.suptitle("Distribution de la longueur des textes par label")
plt.show()

In [ ]:
# Séparation des deux groupes
df_human = sample_df[sample_df["label"] == "human"]
df_other = sample_df[sample_df["label"] != "human"]

# Création des subplots
fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=True)

# Histogramme pour les textes humains
axes[0].hist(df_human["text_len"], bins=30, color="mediumseagreen", edgecolor="black")
axes[0].set_title("Label: Human")
axes[0].set_xlabel("Longueur du texte")
axes[0].set_ylabel("Nombre de textes")

# Histogramme pour les autres textes
axes[1].hist(df_other["text_len"], bins=30, color="steelblue", edgecolor="black")
axes[1].set_title("Label: LLMs (GPT2, GPT3, LLAMA)")
axes[1].set_xlabel("Longueur du texte")

plt.suptitle("Distribution de la longueur des textes : Human vs LLMs", fontsize=14)
plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

In [ ]:
all_stopwords = STOPWORDS

# Liste des labels à traiter
labels = sample_df.label.unique()

for label in labels:
    # Sélection du texte pour ce label
    text = sample_df[sample_df.label == label].text.str.lower().str.cat(sep=' ')
    
    # Nettoyage optionnel : suppression ponctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    # Création du WordCloud
    wc = WordCloud(width=800, height=800,
                   background_color="white",
                   stopwords=all_stopwords,
                   min_font_size=10)
    
    cloud = wc.generate(text)
    
    # Affichage
    plt.figure(figsize=(8, 8))
    plt.imshow(cloud, interpolation='bilinear')
    plt.axis("off")
    plt.title(f"Word Cloud - {label}", fontsize=14)
    plt.tight_layout()
    plt.show()

In [ ]:
# Textes pour chaque groupe
text_human = sample_df[sample_df.label == 'human'].text.str.lower().str.cat(sep=' ')
text_other = sample_df[sample_df.label != 'human'].text.str.lower().str.cat(sep=' ')

# Nettoyage optionnel
text_human = re.sub(r'[^\w\s]', '', text_human)
text_other = re.sub(r'[^\w\s]', '', text_other)

# Création des WordClouds
wc = WordCloud(width=800, height=800,
               background_color="white",
               stopwords=all_stopwords,
               min_font_size=10)

cloud_human = wc.generate(text_human)
cloud_other = wc.generate(text_other)

# Affichage côte à côte
fig, axs = plt.subplots(1, 2, figsize=(16, 8))

axs[0].imshow(cloud_human, interpolation='bilinear')
axs[0].axis("off")
axs[0].set_title("Word Cloud - Human")

axs[1].imshow(cloud_other, interpolation='bilinear')
axs[1].axis("off")
axs[1].set_title("Word Cloud - Models (GPT-3/4, LLaMA)")

plt.tight_layout()
plt.show()

## Analyse descriptive des caractéristiques (stylistiques, de complexité, psychologique)

In [ ]:
# Caractéristiques stylistiques 
## Quote Frequency (QF) : fréquence des guillemets ", ', «, », etc.
## Ponctuation Frequency (PF)  : fréquence des ., ;, :, !, ?, etc.
## Punctuation Types (PT) : nombre de formes uniques de ponctuation
## Exclamation Frequency (EF) : fréquence des points d'exclamation !
## Stopwords Frequency (SWF) : fréquence des mots vides (stopwords) (en utilisant nltk)
## Camel-Case Frequency (CCF) : fréquence des mots commençant par une majuscule suivi d'au moins une minuscule
## Négations Frequency (NF) : fréquence des mots de négation (not, no, never, etc.)
## Noms propres Frequency (NPF) :  fréquence des étiquettes POS NNP et NNPS
## Mentions d'utilisateurs : Fréquence de @
## Hashtags : Fréquence de #
## Mots mals orthographiés : Fréquence de mots non considérés comme valide par PyEnchant
## Mots manquants dans le vocabulaire : Fréquence de mots non présents dans le dictionnaire de SentiWordNet
## Noms : Fréquence de POS tags NN, NNS, NNP, NNPS
## Mots au passé : Fréquence de POS tags VBD, VBN
## Verbes : Fréquence de POS tags VB, VBP, VBZ, VBD et VBG
## Mots interrogatifs : Fréquence de POS tags WRB, WDT et WP

# Caractéristiques de complexité
## Nombre de mots : nombre total de mots
## Longueur moyenne des mots : nombre moyen de caractères par mot
## TTR : Rapport entre le nombre de mots de vocabulaire uniques et le nombre total de mots
## MTLD : Mesure du TTR pour des segments de texte de plus en plus longs

# Caractéristique psychologique
## Score de sentiment : somme des scores SentiWordNet pour tous les mots de vocabulaire disponibles

In [ ]:
# Résumé global (moyenne, écart-type, min, max, médiane) pour chaque caractéristique.
train_df.describe()
test_df.describe()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Corrélation entre les caractéristiques : pour détecter des redondances ou structures.

plt.figure(figsize=(14, 10))
sns.heatmap(train_df.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Corrélation entre caractéristiques")

In [ ]:
import seaborn as sns
# Analyse des caractéristiques par label
feature_list = [
    'quote_frequency', 'punctuation_count', 'unique_punctuation_count', 'exclamation_frequency', 'stopword_frequency', 'camel_case_frequency', 'negation_frequency', 'proper_noun_frequency',
    'user_mentions_frequency', 'hashtag_frequency', 'misspelled_words',
    'oov_frequency', 'noun_frequency', 'past_tense_frequency',
    'verb_frequency', 'interrogative_frequency', 
    'word_count', 'mean_word_length', 'ttr', 'mtld',
    'sentiment_score',
    # Ajoutez d'autres caractéristiques si nécessaire
]
# Créer des boxplots pour chaque caractéristique par label : données d'entraînement
for feature in feature_list:
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.show()

# Créer des boxplots pour chaque caractéristique par label : données de test
for feature in feature_list:
    sns.boxplot(x='label', y=feature, data=test_df)
    plt.title(f'{feature} par label')
    plt.show()

In [ ]:
# Analyse des caractéristiques stylistiques 
stylistic_features = [
    'quote_frequency', 'punctuation_count', 'unique_punctuation_count', 'exclamation_frequency', 'stopword_frequency', 'camel_case_frequency', 'negation_frequency', 'proper_noun_frequency',
    'user_mentions_frequency', 'hashtag_frequency', 'misspelled_words',
    'oov_frequency', 'noun_frequency', 'past_tense_frequency',
    'verb_frequency', 'interrogative_frequency'
]

# Boxplots
for feature in stylistic_features:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.tight_layout()
    plt.show()

# T-tests
print("=== T-tests caractéristiques stylistiques ===")
for feature in stylistic_features:
    group0 = train_df[train_df['label'] == 0][feature]
    group1 = train_df[train_df['label'] == 1][feature]
    stat, p = ttest_ind(group0, group1, equal_var=False)
    print(f"{feature:30s} p-value = {p:.4f}")

In [ ]:
# Analyse des caractéristiques de complexité
complexity_features = [
    'word_count', 'mean_word_length', 'ttr', 'mtld'
]

# Boxplots
for feature in complexity_features:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.tight_layout()
    plt.show()

# T-tests
print("=== T-tests caractéristiques de complexité ===")
for feature in complexity_features:
    group0 = train_df[train_df['label'] == 0][feature]
    group1 = train_df[train_df['label'] == 1][feature]
    stat, p = ttest_ind(group0, group1, equal_var=False)
    print(f"{feature:30s} p-value = {p:.4f}")

In [ ]:
# Analyse des caractéristiques psychologiques
psychological_features = [
    'sentiment_score'
]

# Boxplots
for feature in psychological_features:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.tight_layout()
    plt.show()

# T-tests
print("=== T-tests caractéristiques psychologiques ===")
for feature in psychological_features:
    group0 = train_df[train_df['label'] == 0][feature]
    group1 = train_df[train_df['label'] == 1][feature]
    stat, p = ttest_ind(group0, group1, equal_var=False)
    print(f"{feature:30s} p-value = {p:.4f}")

# Modélisation
BERT, RoBERTa, SentenceBERT (+ différents tokenizers),... à comparer avec les caractéristiques définies dans papier

In [26]:
train_df = pd.read_json('data/en_train_all_features.jsonl', lines=True)
test_df = pd.read_json('data/en_test_all_features.jsonl', lines=True)

In [27]:
train_df.shape

(9600, 30)

In [29]:
test_df.shape

(2400, 30)

## Classifier par embeddings (TF-IDF, Bag-of-Words, BERT, RoBERTa, SentenceBERT)

In [30]:
train_df['labels'] = train_df['label'].apply(lambda x: 0 if x == 'human' else 1)

In [31]:
text_train = train_df['text']
text_test = test_df['text']

In [32]:
test_df['labels'] = test_df['label'].apply(lambda x: 0 if x == 'human' else 1)

### Bag-of-words

In [68]:
x_train_bow = train_df['bow_vector']
y_train_bow = train_df['labels']

In [69]:
x_test_bow = test_df['bow_vector']
y_test_bow = test_df['labels']

In [70]:
vectorizer = CountVectorizer(max_features=1000)  
vectorizer.fit(text_train)

CountVectorizer(max_features=1000)

In [73]:
# Sauvegarde du scaler 
joblib.dump(vectorizer, 'outputs/vectorizers/bow_vectorizer.pkl')

['outputs/vectorizers/bow_vectorizer.pkl']

In [74]:
# Appliquer la vectorisation BoW sur les textes
x_train_bow_vectorized = vectorizer.transform(text_train).toarray()
x_test_bow_vectorized = vectorizer.transform(text_test).toarray()

In [75]:
# Normalisation (important pour SVM notamment)
scaler_bow = StandardScaler()
x_train_bow_scaled = scaler_bow.fit_transform(x_train_bow_vectorized)
x_test_bow_scaled = scaler_bow.transform(x_test_bow_vectorized)

In [77]:
# Sauvegarde du scaler 
joblib.dump(scaler_bow, 'outputs/scalers/bow_scaler.pkl')

['outputs/scalers/bow_scaler.pkl']

In [78]:
# Pour Bag of Words
results_bow = train_and_tune_models(x_train_bow_scaled, y_train_bow, x_test_bow_scaled, y_test_bow, feature_type='bow')

Training and tuning LogisticRegression_bow...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LogisticRegression_bow: {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
Training time: 2.64 seconds
LogisticRegression_bow enregistré dans outputs/models/LogisticRegression_bow_model.joblib ✅

Training and tuning LinearSVC_bow...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LinearSVC_bow: {'C': 0.01, 'loss': 'squared_hinge'}
Training time: 8.57 seconds
LinearSVC_bow enregistré dans outputs/models/LinearSVC_bow_model.joblib ✅

Training and tuning XGBoost_bow...
Fitting 3 folds for each of 8 candidates, totalling 24 fits

/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:33] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:33] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:33] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:33] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:34] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:34] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:34] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:36] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:36] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:36] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:01:40] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best params for XGBoost_bow: {'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 200}
Training time: 10.05 seconds
XGBoost_bow enregistré dans outputs/models/XGBoost_bow_model.joblib ✅

In [79]:
results_bow

,Model,Best Params,Accuracy,F1-Score,Precision,Recall,Training Time (s)
0,LogisticRegression_bow,"{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}",0.621250,0.621255,0.621308,0.621250,2.635272
1,LinearSVC_bow,"{'C': 0.01, 'loss': 'squared_hinge'}",0.620833,0.620840,0.620877,0.620833,8.574489
2,XGBoost_bow,"{'learning_rate': 0.1, 'max_depth': 6, 'n_esti...",0.690000,0.689998,0.689996,0.690000,10.049232

### TF-IDF

In [80]:
x_train_tfidf = train_df['tfidf_vector']
y_train_tfidf = train_df['labels']

x_test_tfidf = test_df['tfidf_vector']
y_test_tfidf = test_df['labels']

In [81]:
tfidf_vectorizer = TfidfVectorizer(max_features=1000)
tfidf_vectorizer.fit(text_train)

TfidfVectorizer(max_features=1000)

In [82]:
# Sauvegarde du scaler 
joblib.dump(tfidf_vectorizer, 'outputs/vectorizers/tfidf_vectorizer.pkl')

['outputs/vectorizers/tfidf_vectorizer.pkl']

In [83]:
# Appliquer la vectorisation TF-IDF sur les textes
x_train_tfidf_vectorized = tfidf_vectorizer.transform(text_train).toarray()
x_test_tfidf_vectorized = tfidf_vectorizer.transform(text_test).toarray()

# Normalisation
scaler_tfidf = StandardScaler()
x_train_tfidf_scaled = scaler_tfidf.fit_transform(x_train_tfidf_vectorized)
x_test_tfidf_scaled = scaler_tfidf.transform(x_test_tfidf_vectorized)

In [84]:
# Sauvegarde du scaler 
joblib.dump(scaler_tfidf, 'outputs/scalers/tfidf_scaler.pkl')

['outputs/scalers/tfidf_scaler.pkl']

In [85]:
# Pour TF-IDF
results_tfidf = train_and_tune_models(x_train_tfidf_scaled, y_train_tfidf, x_test_tfidf_scaled, y_test_tfidf, feature_type='tfidf')

Training and tuning LogisticRegression_tfidf...
Fitting 3 folds for each of 4 candidates, totalling 12 fits

Best params for LogisticRegression_tfidf: {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
Training time: 1.84 seconds
LogisticRegression_tfidf enregistré dans outputs/models/LogisticRegression_tfidf_model.joblib ✅

Training and tuning LinearSVC_tfidf...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LinearSVC_tfidf: {'C': 0.01, 'loss': 'squared_hinge'}
Training time: 4.44 seconds
LinearSVC_tfidf enregistré dans outputs/models/LinearSVC_tfidf_model.joblib ✅

Training and tuning XGBoost_tfidf...
Fitting 3 folds for each of 8 candidates, totalling 24 fits

/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:06] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:07] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:07] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:12] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:20] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:20] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:21] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:03:45] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best params for XGBoost_tfidf: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
Training time: 43.29 seconds
XGBoost_tfidf enregistré dans outputs/models/XGBoost_tfidf_model.joblib ✅

In [86]:
results_tfidf

,Model,Best Params,Accuracy,F1-Score,Precision,Recall,Training Time (s)
0,LogisticRegression_tfidf,"{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}",0.627083,0.627088,0.627098,0.627083,1.844202
1,LinearSVC_tfidf,"{'C': 0.01, 'loss': 'squared_hinge'}",0.625417,0.625418,0.625419,0.625417,4.440465
2,XGBoost_tfidf,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.651250,0.651111,0.651315,0.651250,43.290054

### BERT

In [87]:
x_train_bert = train_df['bert_embedding']
y_train_bert = train_df['labels']

In [88]:
x_test_bert = test_df['bert_embedding']
y_test_bert = test_df['labels']

In [89]:
# Normalisation des embeddings
scaler = StandardScaler()
x_train_bert_scaled = scaler.fit_transform(np.array(x_train_bert.to_list()))
x_test_bert_scaled = scaler.transform(np.array(x_test_bert.to_list()))

In [90]:
# Sauvegarde du scaler 
joblib.dump(scaler, 'outputs/scalers/bert_scaler.pkl')

['outputs/scalers/bert_scaler.pkl']

In [91]:
y_test_bert = np.array(y_test_bert.to_list())
y_train_bert = np.array(y_train_bert.to_list())

In [92]:
# Pour BERT embeddings
results_bert = train_and_tune_models(x_train_bert_scaled, y_train_bert, x_test_bert_scaled, y_test_bert, feature_type='bert')

Training and tuning LogisticRegression_bert...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LogisticRegression_bert: {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
Training time: 7.58 seconds
LogisticRegression_bert enregistré dans outputs/models/LogisticRegression_bert_model.joblib ✅

Training and tuning LinearSVC_bert...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LinearSVC_bert: {'C': 0.01, 'loss': 'squared_hinge'}
Training time: 11.52 seconds
LinearSVC_bert enregistré dans outputs/models/LinearSVC_bert_model.joblib ✅

Training and tuning XGBoost_bert...
Fitting 3 folds for each of 8 candidates, totalling 24 fits

/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:11] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:11] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:11] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:11] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:18] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:18] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:20] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:26] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:26] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:04:26] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:05:16] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best params for XGBoost_bert: {'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 200}
Training time: 76.71 seconds
XGBoost_bert enregistré dans outputs/models/XGBoost_bert_model.joblib ✅

In [93]:
results_bert

,Model,Best Params,Accuracy,F1-Score,Precision,Recall,Training Time (s)
0,LogisticRegression_bert,"{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}",0.807500,0.807300,0.808400,0.807500,7.584945
1,LinearSVC_bert,"{'C': 0.01, 'loss': 'squared_hinge'}",0.812500,0.812334,0.813256,0.812500,11.519580
2,XGBoost_bert,"{'learning_rate': 0.1, 'max_depth': 6, 'n_esti...",0.784583,0.784511,0.784773,0.784583,76.709365

### RoBERTa

In [94]:
x_train_roberta = train_df['roberta_embedding']
y_train_roberta = train_df['labels']

In [95]:
x_test_roberta = test_df['roberta_embedding']
y_test_roberta = test_df['labels']

In [96]:
# Normalisation des embeddings
scaler = StandardScaler()
x_train_roberta_scaled = scaler.fit_transform(np.array(x_train_roberta.to_list()))
x_test_roberta_scaled = scaler.transform(np.array(x_test_roberta.to_list()))

In [97]:
# Sauvegarde du scaler 
joblib.dump(scaler, 'outputs/scalers/roberta_scaler.pkl')

['outputs/scalers/roberta_scaler.pkl']

In [98]:
y_test_roberta = np.array(y_test_roberta.to_list())
y_train_roberta = np.array(y_train_roberta.to_list())

In [101]:
# Pour RoBERTa embeddings
results_roberta = train_and_tune_models(x_train_roberta_scaled, y_train_roberta, x_test_roberta_scaled, y_test_roberta, feature_type='roberta')

Training and tuning LogisticRegression_roberta...
Fitting 3 folds for each of 4 candidates, totalling 12 fits

Best params for LogisticRegression_roberta: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
Training time: 14.37 seconds
LogisticRegression_roberta enregistré dans outputs/models/LogisticRegression_roberta_model.joblib ✅

Training and tuning LinearSVC_roberta...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LinearSVC_roberta: {'C': 0.01, 'loss': 'squared_hinge'}
Training time: 10.25 seconds
LinearSVC_roberta enregistré dans outputs/models/LinearSVC_roberta_model.joblib ✅

Training and tuning XGBoost_roberta...
Fitting 3 folds for each of 8 candidates, totalling 24 fits

/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:17] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:17] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:18] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:18] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:18] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:23] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:24] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:06:24] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best params for XGBoost_roberta: {'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 200}
Training time: 71.36 seconds
XGBoost_roberta enregistré dans outputs/models/XGBoost_roberta_model.joblib ✅

In [102]:
results_roberta

,Model,Best Params,Accuracy,F1-Score,Precision,Recall,Training Time (s)
0,LogisticRegression_roberta,"{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}",0.897083,0.897079,0.897099,0.897083,14.371660
1,LinearSVC_roberta,"{'C': 0.01, 'loss': 'squared_hinge'}",0.897500,0.897493,0.897531,0.897500,10.251628
2,XGBoost_roberta,"{'learning_rate': 0.1, 'max_depth': 6, 'n_esti...",0.867917,0.867905,0.868262,0.867917,71.359165

### SentenceBERT

In [103]:
x_train_sbert = train_df['sbert_embedding']
y_train_sbert = train_df['labels']

In [104]:
x_test_sbert = test_df['sbert_embedding']
y_test_sbert = test_df['labels']

In [105]:
# Normalisation des embeddings
scaler = StandardScaler()
x_train_sbert_scaled = scaler.fit_transform(np.array(x_train_sbert.to_list()))
x_test_sbert_scaled = scaler.transform(np.array(x_test_sbert.to_list()))

In [106]:
# Sauvegarde du scaler 
joblib.dump(scaler, 'outputs/scalers/sbert_scaler.pkl')

['outputs/scalers/sbert_scaler.pkl']

In [107]:
y_test_sbert = np.array(y_test_sbert.to_list())
y_train_sbert = np.array(y_train_sbert.to_list())

In [108]:
# Pour SentenceBERT
results_sbert = train_and_tune_models(x_train_sbert_scaled, y_train_sbert, x_test_sbert_scaled, y_test_sbert, feature_type='sbert')

Training and tuning LogisticRegression_sbert...
Fitting 3 folds for each of 4 candidates, totalling 12 fits

Best params for LogisticRegression_sbert: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
Training time: 3.87 seconds
LogisticRegression_sbert enregistré dans outputs/models/LogisticRegression_sbert_model.joblib ✅

Training and tuning LinearSVC_sbert...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LinearSVC_sbert: {'C': 0.01, 'loss': 'squared_hinge'}
Training time: 6.85 seconds
LinearSVC_sbert enregistré dans outputs/models/LinearSVC_sbert_model.joblib ✅

Training and tuning XGBoost_sbert...
Fitting 3 folds for each of 8 candidates, totalling 24 fits

/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:32] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:35] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:36] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:36] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:38] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:38] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:38] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:07:59] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best params for XGBoost_sbert: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100}
Training time: 28.46 seconds
XGBoost_sbert enregistré dans outputs/models/XGBoost_sbert_model.joblib ✅

## Classifier par caractéristiques (stylistiques, de complexité, psychologique)

In [124]:
handcrafted_columns = [
    'quote_frequency', 'punctuation_count', 'unique_punctuation_count', 'exclamation_frequency',
    'stopword_frequency', 'camel_case_frequency', 'negation_frequency',
    'proper_noun_frequency', 'user_mentions_frequency', 'hashtag_frequency',
    'misspelled_words', 'oov_frequency', 'noun_frequency',
    'past_tense_frequency', 'verb_frequency', 'interrogative_frequency',
    'word_count', 'mean_word_lenght', 'ttr', 'mtld', 'sentiment_score'
]

x_train_handcrafted = train_df[handcrafted_columns]
y_train_handcrafted = train_df['labels']

x_test_handcrafted = test_df[handcrafted_columns]
y_test_handcrafted = test_df['labels']

In [125]:
x_train_handcrafted = np.array(x_train_handcrafted)
y_train_handcrafted = np.array(y_train_handcrafted.to_list())

In [126]:
x_test_handcrafted = np.array(x_test_handcrafted)
y_test_handcrafted = np.array(y_test_handcrafted.to_list())

In [127]:
x_train_handcrafted_fixed = np.array([
    [float(el[0]) if isinstance(el, list) else float(el) for el in row]
    for row in x_train_handcrafted
])

x_test_handcrafted_fixed = np.array([
    [float(el[0]) if isinstance(el, list) else float(el) for el in row]
    for row in x_test_handcrafted
])

In [128]:
x_test_handcrafted_fixed.shape

(2400, 21)

In [129]:
# Ensuite normaliser les features
scaler_handcrafted = StandardScaler()
x_train_handcrafted_scaled = scaler_handcrafted.fit_transform(x_train_handcrafted_fixed)
x_test_handcrafted_scaled = scaler_handcrafted.transform(x_test_handcrafted_fixed)

In [130]:
joblib.dump(scaler_handcrafted, "outputs/scalers/handcrafted_scaler.pkl")

['outputs/scalers/handcrafted_scaler.pkl']

In [131]:
# Pour Handcrafted features
results_handcrafted = train_and_tune_models(x_train_handcrafted_scaled, y_train_handcrafted, x_test_handcrafted_scaled, y_test_handcrafted, feature_type='handcrafted')

Training and tuning LogisticRegression_handcrafted...
Fitting 3 folds for each of 4 candidates, totalling 12 fits

Best params for LogisticRegression_handcrafted: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
Training time: 3.21 seconds
LogisticRegression_handcrafted enregistré dans outputs/models/LogisticRegression_handcrafted_model.joblib ✅

Training and tuning LinearSVC_handcrafted...
Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params for LinearSVC_handcrafted: {'C': 0.1, 'loss': 'squared_hinge'}
Training time: 1.42 seconds
LinearSVC_handcrafted enregistré dans outputs/models/LinearSVC_handcrafted_model.joblib ✅

Training and tuning XGBoost_handcrafted...
Fitting 3 folds for each of 8 candidates, totalling 24 fits

/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:19] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/home/onyxia/work/ENSAE_NLP_project/.venv/lib/python3.12/site-packages/xgboost/training.py:183: UserWarning: [19:43:20] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best params for XGBoost_handcrafted: {'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 200}
Training time: 1.71 seconds
XGBoost_handcrafted enregistré dans outputs/models/XGBoost_handcrafted_model.joblib ✅

In [132]:
results_handcrafted

,Model,Best Params,Accuracy,F1-Score,Precision,Recall,Training Time (s)
0,LogisticRegression_handcrafted,"{'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}",0.665833,0.665746,0.666238,0.665833,3.214934
1,LinearSVC_handcrafted,"{'C': 0.1, 'loss': 'squared_hinge'}",0.668333,0.668256,0.668714,0.668333,1.423614
2,XGBoost_handcrafted,"{'learning_rate': 0.1, 'max_depth': 6, 'n_esti...",0.760417,0.760376,0.760474,0.760417,1.710593