# Import des librairies nécessaires

In [ ]:
import pandas as pd
import json
import numpy as np
import os
import sys
import argparse
import dotenv 
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.dates as mdates
import torch
from transformers import BertTokenizer, BertModel
from transformers import RobertaTokenizer, RobertaModel
from sentence_transformers import SentenceTransformer
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud
from wordcloud import STOPWORDS
from scipy.stats import ttest_ind
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
import re

from sklearn.model_selection import train_test_split

dotenv.load_dotenv()

True

# Chargement des données

données issues de : https://arxiv.org/pdf/2310.08903

https://github.com/Jihuai-wpy/SeqXGPT

In [2]:
# Chargement des données écrites par l'humain
human_lines_path = 'data/en_human_lines.jsonl'
human_df = pd.read_json(human_lines_path, lines=True)
print("Le nombre de textes écrits par l'humaine est  : ", human_df.shape[0])

Le nombre de textes écrits par l'humaine est  :  6000

In [3]:
# Chargement des données générées par le modèle GPT-2
gpt2_lines_path = 'data/en_gpt2_lines.jsonl'
gpt2_df = pd.read_json(gpt2_lines_path, lines=True)
print("Le nombre de textes générés par le modèle GPT-2 est  : ", gpt2_df.shape[0])

Le nombre de textes générés par le modèle GPT-2 est  :  6000

In [4]:
# Chargement des données générées par le modèle GPT-3
gpt3_lines_path = 'data/en_gpt3_lines.jsonl'
gpt3_df = pd.read_json(gpt3_lines_path, lines=True)
print("Le nombre de textes générés par le modèle GPT-3 est  : ", gpt3_df.shape[0])

Le nombre de textes générés par le modèle GPT-3 est  :  6000

In [5]:
# Chargement des données générées par le modèle LLaMA
llama_lines_path = 'data/en_llama_lines.jsonl'
llama_df = pd.read_json(llama_lines_path, lines=True)
print("Le nombre de textes générés par le modèle LLaMA est  : ", llama_df.shape[0])

Le nombre de textes générés par le modèle LLaMA est  :  5904

# Prétraitement des données

## Sélection des données pour la base

In [6]:
# Tirage aléatoire de 2000 textes dans chaque dataframe issu des LLMs
gpt2_sample = gpt2_df.sample(n=2000, random_state=42)
gpt3_sample = gpt3_df.sample(n=2000, random_state=42)
llama_sample = llama_df.sample(n=2000, random_state=42)

# Concaténation des échantillons dans un seul dataframe
sample_df = pd.concat([gpt2_sample, gpt3_sample, llama_sample], ignore_index=True)

# Ajout de toutes les données écrites par l'humain
sample_df = pd.concat([sample_df, human_df], ignore_index=True)

# Mélanger les lignes du dataframe
sample_df = sample_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Ajout d'une colonne pour la longueur des textes
sample_df['text_len'] = sample_df['text'].apply(len)

sample_df = sample_df.drop(columns=["prompt_len"])

# Sauvegarde du dataframe échantillonné dans un fichier JSONL
sample_df.to_json('data/en_sample_lines.jsonl', orient='records', lines=True)

# Affichage du nombre total de textes   
print("Le nombre total de textes est : ", sample_df.shape[0])
# Affichage du nombre de textes par source
print("Le nombre de textes par source est :")
print(sample_df['label'].value_counts())

# Affichage du début du dataframe
print("Aperçu du dataframe échantillonné :")
print(sample_df.head())

Le nombre total de textes est :  12000
Le nombre de textes par source est :
label
human     6000
gpt2      2000
llama     2000
gpt3re    2000
Name: count, dtype: int64
Aperçu du dataframe échantillonné :
                                                text  label  text_len
0  In the triplet form, O 2 molecules are paramag...   gpt2      1477
1  Studies on income inequality and growth have s...  human       605
2  JCF Capital ULC announced on Tuesday a deal wi...   gpt2       424
3  The right to create private schools in Germany...  human       622
4  during the week of 2015-05-11 Aatrox was last ...   gpt2      1361

## Tokenisation du texte

In [39]:
# Tokenisation des textes avec BERT
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize_text_bert(text):
    return bert_tokenizer.tokenize(text)

def tokenize_word(text):
    return word_tokenize(text)

sample_df['bert_tokens'] = sample_df['text'].apply(tokenize_text_bert)
sample_df['word_tokens'] = sample_df['text'].apply(tokenize_word)
sample_df['word_tokens'] = sample_df['word_tokens'].apply(lambda x: [word.lower() for word in x])

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\hp/nltk_data'
    - 'c:\\Users\\hp\\Documents\\ENSAE\\3A\\Deuxième semestre\\NLP\\Projet\\ENSAE_NLP_project\\.venv\\nltk_data'
    - 'c:\\Users\\hp\\Documents\\ENSAE\\3A\\Deuxième semestre\\NLP\\Projet\\ENSAE_NLP_project\\.venv\\share\\nltk_data'
    - 'c:\\Users\\hp\\Documents\\ENSAE\\3A\\Deuxième semestre\\NLP\\Projet\\ENSAE_NLP_project\\.venv\\lib\\nltk_data'
    - 'C:\\Users\\hp\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

## Découpe de la base de données en base d'entraînement et base de test

In [8]:
# Découpe de la base de données en base d'entraînement et de test (80% - 20%)
train_df, test_df = train_test_split(sample_df, test_size=0.2, random_state=42)
# Sauvegarde des dataframes d'entraînement et de test dans des fichiers JSONL
train_df.to_json('data/en_train_lines.jsonl', orient='records', lines=True)
test_df.to_json('data/en_test_lines.jsonl', orient='records', lines=True)

In [ ]:
text_train = train_df['text']
label_train = train_df['label']
bert_token_train = train_df['bert_tokens']
word_token_train = train_df['word_tokens']

text_test = test_df['text']
label_test = test_df['label']
bert_token_test = test_df['bert_tokens']
word_token_test = test_df['word_tokens']

In [10]:
sample_df.head()

,text,label,text_len,tokens
0,"In the triplet form, O 2 molecules are paramag...",gpt2,1477,"[in, the, triple, ##t, form, ,, o, 2, molecule..."
1,Studies on income inequality and growth have s...,human,605,"[studies, on, income, inequality, and, growth,..."
2,JCF Capital ULC announced on Tuesday a deal wi...,gpt2,424,"[jc, ##f, capital, ul, ##c, announced, on, tue..."
3,The right to create private schools in Germany...,human,622,"[the, right, to, create, private, schools, in,..."
4,during the week of 2015-05-11 Aatrox was last ...,gpt2,1361,"[during, the, week, of, 2015, -, 05, -, 11, aa..."

## Définition de caractéristiques des données

### Embeddings des textes

In [11]:
# Encodage des textes avec Bag-of-word
# Créer et entraîner le vectorizer
vectorizer = CountVectorizer(max_features=1000)  # Limiter à 1000 mots les plus fréquents
# Entraîner le vectorizer sur les textes d'entraînement
vectorizer.fit(text_train)

# Transformer les textes d'entraînement et de test en vecteurs
text_train_counts = vectorizer.transform(text_train)
text_test_counts = vectorizer.transform(text_test)

# On transforme tous les textes en vecteurs
bow_vectors = vectorizer.transform(sample_df["text"]).toarray().tolist()

# Et on ajoute la colonne
sample_df["bow_vector"] = bow_vectors

In [12]:
# Encodage des textes avec TF-IDF
# Création du vectorizer avec 1000 mots max
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

# Apprentissage du vocabulaire sur les textes d'entraînement
tfidf_vectorizer.fit(text_train)

# Transformation des textes d'entraînement et de test en vecteurs TF-IDF
text_train_tfidf = tfidf_vectorizer.transform(text_train)
text_test_tfidf = tfidf_vectorizer.transform(text_test)

# Application sur tous les textes du dataset
tfidf_vectors = tfidf_vectorizer.transform(sample_df["text"])

# Conversion en liste et ajout au DataFrame
sample_df["tfidf_vector"] = tfidf_vectors.toarray().tolist()

In [13]:
sample_df.head()

,text,label,text_len,tokens,bow_vector,tfidf_vector
0,"In the triplet form, O 2 molecules are paramag...",gpt2,1477,"[in, the, triple, ##t, form, ,, o, 2, molecule...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,Studies on income inequality and growth have s...,human,605,"[studies, on, income, inequality, and, growth,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,JCF Capital ULC announced on Tuesday a deal wi...,gpt2,424,"[jc, ##f, capital, ul, ##c, announced, on, tue...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,The right to create private schools in Germany...,human,622,"[the, right, to, create, private, schools, in,...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0.0, 0.0, 0.0, 0.0, 0.09888393745632554, 0.0,..."
4,during the week of 2015-05-11 Aatrox was last ...,gpt2,1361,"[during, the, week, of, 2015, -, 05, -, 11, aa...","[0, 16, 0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,...","[0.0, 0.3365636073184281, 0.0, 0.0, 0.13240910..."

In [ ]:
# Embedding des tokens avec Word2Vec (à entraîner sur les données d'entraînement)
w2v_model = Word2Vec(sentences=bert_token_train.tolist(), vector_size=100, window=5, min_count=1, workers=4)

def get_text_embedding(tokens, model, vector_size=100):
    vecs = [model.wv[word] for word in tokens if word in model.wv]
    if len(vecs) > 0:
        return np.mean(vecs, axis=0)
    else:
        return np.zeros(vector_size)

# Appliquer à chaque ligne pour créer une colonne d'embedding
sample_df['w2v_embedding'] = sample_df['tokens'].apply(lambda tokens: get_text_embedding(tokens, w2v_model, vector_size=100))

In [17]:
# Transformer les textes d'entraînement et de test en embeddings Word2Vec
text_train_w2v = text_train.apply(lambda tokens: get_text_embedding(tokens, w2v_model, vector_size=100))
text_test_w2v = text_test.apply(lambda tokens: get_text_embedding(tokens, w2v_model, vector_size=100))

In [23]:
type(text_test)

pandas.core.series.Series

In [ ]:
# Embedding des textes avec BERT

# Charger le modèle pré-entraîné BERT
model = BertModel.from_pretrained('bert-base-uncased')

# Tokenisation et extraction des embeddings
def get_bert_embedding(tokens):
    inputs = bert_tokenizer(tokens, padding=True, truncation=True, return_tensors="pt", is_split_into_words=True)
    
    # Passer les tokens dans le modèle BERT pour obtenir les embeddings
    with torch.no_grad():
        outputs = model(**inputs)
    
    # Extraire les embeddings de la dernière couche cachée et en faire la moyenne
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()

# Transformer les textes d'entraînement et de test en embeddings BERT
text_train_bert = bert_token_train.apply(get_bert_embedding)
text_test_bert = bert_token_test.apply(get_bert_embedding)

# Appliquer à chaque ligne pour créer une colonne d'embedding BERT
# sample_df['bert_embedding'] = sample_df['text'].apply(get_bert_embedding)

KeyboardInterrupt:

In [ ]:
# Embedding des textes avec RoBERTa
# Charger le modèle pré-entraîné RoBERTa et le tokenizer
roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
roberta_model = RobertaModel.from_pretrained('roberta-base')

# Tokenisation et extraction des embeddings
def get_roberta_embedding(tokens):
    inputs = roberta_tokenizer(tokens, padding=True, truncation=True, return_tensors="pt", is_split_into_words=True)
    
    with torch.no_grad():
        outputs = roberta_model(**inputs)
    
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()

# Transformer les textes d'entraînement et de test en embeddings RoBERTa
text_train_roberta = bert_token_train.apply(get_roberta_embedding)
text_test_roberta = bert_token_test.apply(get_roberta_embedding)

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

c:\Users\hp\Documents\ENSAE\3A\Deuxième semestre\NLP\Projet\ENSAE_NLP_project\.venv\Lib\site-packages\huggingface_hub\file_download.py:144: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hp\.cache\huggingface\hub\models--roberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

KeyboardInterrupt:

In [ ]:
# Embedding des textes avec Sentence-BERT

# Charger le modèle Sentence-BERT
sbert_model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Tokenisation et extraction des embeddings
def get_sbert_embedding(tokens):
    # Joindre les tokens pour former la phrase
    text = ' '.join(tokens)
    return sbert_model.encode(text)

# Transformer les textes d'entraînement et de test en embeddings Sentence-BERT
text_train_sbert = bert_token_train.apply(get_sbert_embedding)
text_test_sbert = bert_token_test.apply(get_sbert_embedding)

KeyboardInterrupt:

### Caractéristiques issues de https://aclanthology.org/2022.coling-1.573.pdf

In [40]:
from src.features_definition import extract_stylistic_features, extract_complexity_features, extract_psychological_features

In [ ]:
# Caractéristiques stylistiques 
## Quote Frequency (QF) : fréquence des guillemets ", ', «, », etc.
## Ponctuation Frequency (PF)  : fréquence des ., ;, :, !, ?, etc.
## Punctuation Types (PT) : nombre de formes uniques de ponctuation
## Exclamation Frequency (EF) : fréquence des points d'exclamation !
## Stopwords Frequency (SWF) : fréquence des mots vides (stopwords) (en utilisant nltk)
## Camel-Case Frequency (CCF) : fréquence des mots commençant par une majuscule suivi d'au moins une minuscule
## Négations Frequency (NF) : fréquence des mots de négation (not, no, never, etc.)
## Noms propres Frequency (NPF) :  fréquence des étiquettes POS NNP et NNPS
## Mentions d'utilisateurs : Fréquence de @
## Hashtags : Fréquence de #
## Mots mals orthographiés : Fréquence de mots non considérés comme valide par PyEnchant
## Mots manquants dans le vocabulaire : Fréquence de mots non présents dans le dictionnaire de SentiWordNet
## Noms : Fréquence de POS tags NN, NNS, NNP, NNPS
## Mots au passé : Fréquence de POS tags VBD, VBN
## Verbes : Fréquence de POS tags VB, VBP, VBZ, VBD et VBG
## Mots interrogatifs : Fréquence de POS tags WRB, WDT et WP

# Caractéristiques de complexité
## Nombre de mots : nombre total de mots
## Longueur moyenne des mots : nombre moyen de caractères par mot
## TTR : Rapport entre le nombre de mots de vocabulaire uniques et le nombre total de mots
## MTLD : Mesure du TTR pour des segments de texte de plus en plus longs

# Caractéristique psychologique
## Score de sentiment : somme des scores SentiWordNet pour tous les mots de vocabulaire disponibles

In [ ]:
word_token_test

1935     [for, targeted, delivery, of, col, ##loid, ##s...
6494     [the, type, ia, super, ##nova, (, s, ##n, ia, ...
1720     [the, buzz, for, this, film, has, always, been...
9120     [this, article, reviews, the, research, progra...
360      [okay, ,, i, ', ve, watched, this, movie, twic...
                               ...
1195     [strange, ##ness, signature, of, of, qu, ##ark...
11877    [a, group, of, 14, cleaner, ##s, employed, by,...
5421     [on, sunday, ,, president, barack, obama, trav...
3855     [pharmacy, inform, ##atics, is, the, combinati...
4414     [mo, ##to, ##cross, ##ed, was, fun, ,, but, it...
Name: tokens, Length: 2400, dtype: object

In [41]:
# Caractéristiques stylistiques pour données d'entraînement 
extractor_stylistic_train = extract_stylistic_features(text_train, word_token_train)
stylistic_features_train = extractor_stylistic_train.extract_features()

# Caractéristiques stylistiques pour données de test
extractor_stylistic_test = extract_stylistic_features(text_test, word_token_test)
stylistic_features_test = extractor_stylistic_test.extract_features()

NameError: name 'word_token_train' is not defined

In [ ]:
# Caractéristiques complexité pour données d'entraînement
extractor_complexity_train = extract_complexity_features(text_train, word_token_train)
complexity_features_train = extractor_complexity_train.extract_features()

# Caractéristiques complexité pour données de test
extractor_complexity_test = extract_complexity_features(text_test, word_token_test)
complexity_features_test = extractor_complexity_test.extract_features()

In [ ]:
# Caractéristiques psychologiques pour données d'entraînement
extractor_sentiment_train = extract_psychological_features(text_train, word_token_train)
sentiment_features_train = extractor_sentiment_train.extract_features()

# Caractéristiques psychologiques pour données de test
extractor_sentiment_test = extract_psychological_features(text_test, word_token_test)
sentiment_features_test = extractor_sentiment_test.extract_features()

Regroupement de toutes les features pour les données d'entraînement et de test

In [ ]:
# Regrouper les features stylistiques, de complexité et psychologiques, les textes et les embeddings des données d'entraînement
train_df = pd.DataFrame({
    'text': text_train,
    'label': label_train,
    'bert_tokens': bert_token_train,
    'word_tokens': word_token_train,
    'bow_vector': text_train_counts.toarray().tolist(),
    'tfidf_vector': text_train_tfidf.toarray().tolist(),
    'w2v_embedding': text_train_w2v.tolist(),
    'bert_embedding': text_train_bert.tolist(),
    'roberta_embedding': text_train_roberta.tolist(),
    'sbert_embedding': text_train_sbert.tolist(),
})
train_df = pd.concat([train_df, stylistic_features_train, complexity_features_train, sentiment_features_train], axis=1)

# Regrouper les features stylistiques, de complexité et psychologiques, les textes et les embeddings des données de test
test_df = pd.DataFrame({
    'text': text_test,
    'label': label_test,
    'bert_tokens': bert_token_test,
    'word_tokens': word_token_test,
    'bow_vector': text_test_counts.toarray().tolist(),
    'tfidf_vector': text_test_tfidf.toarray().tolist(),
    'w2v_embedding': text_test_w2v.tolist(),
    'bert_embedding': text_test_bert.tolist(),
    'roberta_embedding': text_test_roberta.tolist(),
    'sbert_embedding': text_test_sbert.tolist(),
})
test_df = pd.concat([test_df, stylistic_features_test, complexity_features_test, sentiment_features_test], axis=1)

# Sauvegarde des dataframes d'entraînement et de test dans des fichiers JSONL
train_df.to_json('data/en_train_features.jsonl', orient='records', lines=True)
test_df.to_json('data/en_test_features.jsonl', orient='records', lines=True)

# Analyse descriptive

## Analyse élémentaire

In [ ]:
# Affichage du nombre de textes dans les dataframes d'entraînement et de test
print("Le nombre de textes dans le dataframe d'entraînement est : ", train_df.shape[0])
print("Le nombre de textes dans le dataframe de test est : ", test_df.shape[0])

# Affichage du nombre de textes par source dans les dataframes d'entraînement et de test
print("Le nombre de textes par source dans le dataframe d'entraînement est :")
print(train_df['label'].value_counts())
print("Le nombre de textes par source dans le dataframe de test est :")
print(test_df['label'].value_counts())

In [ ]:
# Affichage de la distribution de la longueur des textes par label

plt.figure(figsize=(10, 6))
sns.violinplot(x="label", y="text_len", data=sample_df)
plt.title("Distribution (violon) de la longueur des textes par label")
plt.xlabel("Label")
plt.ylabel("Longueur du texte")
plt.show()

In [ ]:
# Création du FacetGrid avec un graphique par label
g = sns.FacetGrid(sample_df, col="label", col_wrap=3, height=4, sharex=False, sharey=False)

# Ajout de l'histogramme dans chaque sous-plot
g.map(plt.hist, "text_len", bins=30, color="skyblue", edgecolor="black")

# Ajout des titres et labels
g.set_titles(col_template="Label: {col_name}")
g.set_axis_labels("Longueur du texte", "Nombre de textes")
plt.subplots_adjust(top=0.9)
g.fig.suptitle("Distribution de la longueur des textes par label")
plt.show()

In [ ]:
# Séparation des deux groupes
df_human = sample_df[sample_df["label"] == "human"]
df_other = sample_df[sample_df["label"] != "human"]

# Création des subplots
fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=True)

# Histogramme pour les textes humains
axes[0].hist(df_human["text_len"], bins=30, color="mediumseagreen", edgecolor="black")
axes[0].set_title("Label: Human")
axes[0].set_xlabel("Longueur du texte")
axes[0].set_ylabel("Nombre de textes")

# Histogramme pour les autres textes
axes[1].hist(df_other["text_len"], bins=30, color="steelblue", edgecolor="black")
axes[1].set_title("Label: LLMs (GPT2, GPT3, LLAMA)")
axes[1].set_xlabel("Longueur du texte")

plt.suptitle("Distribution de la longueur des textes : Human vs LLMs", fontsize=14)
plt.tight_layout()
plt.subplots_adjust(top=0.85)
plt.show()

In [ ]:
all_stopwords = STOPWORDS

# Liste des labels à traiter
labels = sample_df.label.unique()

for label in labels:
    # Sélection du texte pour ce label
    text = sample_df[sample_df.label == label].text.str.lower().str.cat(sep=' ')
    
    # Nettoyage optionnel : suppression ponctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    # Création du WordCloud
    wc = WordCloud(width=800, height=800,
                   background_color="white",
                   stopwords=all_stopwords,
                   min_font_size=10)
    
    cloud = wc.generate(text)
    
    # Affichage
    plt.figure(figsize=(8, 8))
    plt.imshow(cloud, interpolation='bilinear')
    plt.axis("off")
    plt.title(f"Word Cloud - {label}", fontsize=14)
    plt.tight_layout()
    plt.show()

In [ ]:
# Textes pour chaque groupe
text_human = sample_df[sample_df.label == 'human'].text.str.lower().str.cat(sep=' ')
text_other = sample_df[sample_df.label != 'human'].text.str.lower().str.cat(sep=' ')

# Nettoyage optionnel
text_human = re.sub(r'[^\w\s]', '', text_human)
text_other = re.sub(r'[^\w\s]', '', text_other)

# Création des WordClouds
wc = WordCloud(width=800, height=800,
               background_color="white",
               stopwords=all_stopwords,
               min_font_size=10)

cloud_human = wc.generate(text_human)
cloud_other = wc.generate(text_other)

# Affichage côte à côte
fig, axs = plt.subplots(1, 2, figsize=(16, 8))

axs[0].imshow(cloud_human, interpolation='bilinear')
axs[0].axis("off")
axs[0].set_title("Word Cloud - Human")

axs[1].imshow(cloud_other, interpolation='bilinear')
axs[1].axis("off")
axs[1].set_title("Word Cloud - Models (GPT-3/4, LLaMA)")

plt.tight_layout()
plt.show()

## Analyse descriptive des caractéristiques (stylistiques, de complexité, psychologique)

In [ ]:
# Caractéristiques stylistiques 
## Quote Frequency (QF) : fréquence des guillemets ", ', «, », etc.
## Ponctuation Frequency (PF)  : fréquence des ., ;, :, !, ?, etc.
## Punctuation Types (PT) : nombre de formes uniques de ponctuation
## Exclamation Frequency (EF) : fréquence des points d'exclamation !
## Stopwords Frequency (SWF) : fréquence des mots vides (stopwords) (en utilisant nltk)
## Camel-Case Frequency (CCF) : fréquence des mots commençant par une majuscule suivi d'au moins une minuscule
## Négations Frequency (NF) : fréquence des mots de négation (not, no, never, etc.)
## Noms propres Frequency (NPF) :  fréquence des étiquettes POS NNP et NNPS
## Mentions d'utilisateurs : Fréquence de @
## Hashtags : Fréquence de #
## Mots mals orthographiés : Fréquence de mots non considérés comme valide par PyEnchant
## Mots manquants dans le vocabulaire : Fréquence de mots non présents dans le dictionnaire de SentiWordNet
## Noms : Fréquence de POS tags NN, NNS, NNP, NNPS
## Mots au passé : Fréquence de POS tags VBD, VBN
## Verbes : Fréquence de POS tags VB, VBP, VBZ, VBD et VBG
## Mots interrogatifs : Fréquence de POS tags WRB, WDT et WP

# Caractéristiques de complexité
## Nombre de mots : nombre total de mots
## Longueur moyenne des mots : nombre moyen de caractères par mot
## TTR : Rapport entre le nombre de mots de vocabulaire uniques et le nombre total de mots
## MTLD : Mesure du TTR pour des segments de texte de plus en plus longs

# Caractéristique psychologique
## Score de sentiment : somme des scores SentiWordNet pour tous les mots de vocabulaire disponibles

In [ ]:
# Résumé global (moyenne, écart-type, min, max, médiane) pour chaque caractéristique.
train_df.describe()
test_df.describe()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Corrélation entre les caractéristiques : pour détecter des redondances ou structures.

plt.figure(figsize=(14, 10))
sns.heatmap(train_df.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Corrélation entre caractéristiques")

In [ ]:
import seaborn as sns
# Analyse des caractéristiques par label
feature_list = [
    'quote_frequency', 'punctuation_count', 'unique_punctuation_count', 'exclamation_frequency', 'stopword_frequency', 'camel_case_frequency', 'negation_frequency', 'proper_noun_frequency',
    'user_mentions_frequency', 'hashtag_frequency', 'misspelled_words',
    'oov_frequency', 'noun_frequency', 'past_tense_frequency',
    'verb_frequency', 'interrogative_frequency', 
    'word_count', 'mean_word_length', 'ttr', 'mtld',
    'sentiment_score',
    # Ajoutez d'autres caractéristiques si nécessaire
]
# Créer des boxplots pour chaque caractéristique par label : données d'entraînement
for feature in feature_list:
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.show()

# Créer des boxplots pour chaque caractéristique par label : données de test
for feature in feature_list:
    sns.boxplot(x='label', y=feature, data=test_df)
    plt.title(f'{feature} par label')
    plt.show()

In [ ]:
# Analyse des caractéristiques stylistiques 
stylistic_features = [
    'quote_frequency', 'punctuation_count', 'unique_punctuation_count', 'exclamation_frequency', 'stopword_frequency', 'camel_case_frequency', 'negation_frequency', 'proper_noun_frequency',
    'user_mentions_frequency', 'hashtag_frequency', 'misspelled_words',
    'oov_frequency', 'noun_frequency', 'past_tense_frequency',
    'verb_frequency', 'interrogative_frequency'
]

# Boxplots
for feature in stylistic_features:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.tight_layout()
    plt.show()

# T-tests
print("=== T-tests caractéristiques stylistiques ===")
for feature in stylistic_features:
    group0 = train_df[train_df['label'] == 0][feature]
    group1 = train_df[train_df['label'] == 1][feature]
    stat, p = ttest_ind(group0, group1, equal_var=False)
    print(f"{feature:30s} p-value = {p:.4f}")

In [ ]:
# Analyse des caractéristiques de complexité
complexity_features = [
    'word_count', 'mean_word_length', 'ttr', 'mtld'
]

# Boxplots
for feature in complexity_features:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.tight_layout()
    plt.show()

# T-tests
print("=== T-tests caractéristiques de complexité ===")
for feature in complexity_features:
    group0 = train_df[train_df['label'] == 0][feature]
    group1 = train_df[train_df['label'] == 1][feature]
    stat, p = ttest_ind(group0, group1, equal_var=False)
    print(f"{feature:30s} p-value = {p:.4f}")

In [ ]:
# Analyse des caractéristiques psychologiques
psychological_features = [
    'sentiment_score'
]

# Boxplots
for feature in psychological_features:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x='label', y=feature, data=train_df)
    plt.title(f'{feature} par label')
    plt.tight_layout()
    plt.show()

# T-tests
print("=== T-tests caractéristiques psychologiques ===")
for feature in psychological_features:
    group0 = train_df[train_df['label'] == 0][feature]
    group1 = train_df[train_df['label'] == 1][feature]
    stat, p = ttest_ind(group0, group1, equal_var=False)
    print(f"{feature:30s} p-value = {p:.4f}")

# Modélisation
Word2Vec, BERT, RoBERTa, SentenceBERT (+ différents tokenizers),... à comparer avec les caractéristiques définies dans papier

## Classifier par caractéristiques

### Modèle MultinomialNB

#### Définition, entraînement et évaluation du modèle :

In [ ]:
# Train a Naive Bayes classifier
# create the MultinomialNB
clf = MultinomialNB()
# Train 
clf.fit(X_train_tf, y_train)
# Evaluate 
print("Score sur l'ensemble d'entraînement :", clf.score(X_train_tf, y_train))
print("Score sur l'ensemble de test :", clf.score(X_test_tf, y_test))
print("Score sur l'ensemble dev:", clf.score(X_dev_tf, y_dev))

#### Analyse des erreurs

In [ ]:
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, confusion_matrix

y_pred = clf.predict(X_test_tf)
print(classification_report(y_test, y_pred))

# Calcul de la matrice de confusion
cm = confusion_matrix(y_test, y_pred, normalize='true')

# Affichage de la matrice de confusion
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=articles_df.category.unique())
disp.plot()

### Autres modèles

## LLM detector

### Définition du modèle

### Test - calcul des performances